#!/usr/bin/perl
#
# read Bob's genotype output in VCF format and output lines in his dat file format.
#
# Output is one line per site with call and quality columns per sample:
# BIN	CHR	START	END	PASS	09C90050	10C103396...	09C90050_CNQ	10C103396_CNQ...
#
# Usage: gunzip -c windows.vcf.gz | vcf2tab > windows.dat

my $j = 1;
while (<>) {
    next if /^\#\#/;
    if (/^\#/) {
	@fields = split;
	@fieldsQual = map { $_ . "_CNQ" } @fields;
	print "BIN\tCHR\tSTART\tEND\tPASS\t",join("\t",@fields[9..$#fields]),"\t",join("\t",@fieldsQual[9..$#fieldsQual]),"\n";
    } else {
	@fields = split;
	(undef, $chr, $start, $end) = split(/_/, $fields[2]);
	@geno = ();
	@qual = ();
	my $pass = 0;  # FT = PASS or LQ
	for ($i=9; $i < @fields; $i++) {
	    @sample = split(/:/, $fields[$i]);
	    ($CN,$CNQ,$FT) = @sample[1,5,6];
	    $pass++ if ($FT =~ /PASS|\./);
	    push(@geno, $CN);
	    push(@qual, $CNQ);
	}
	print "B$j\t$chr\t$start\t$end\t",$pass,"\t",join("\t",@geno),"\t",join("\t",@qual),"\n";
    }
}
