R2sql <- function(data.type) {
  # return an SQL type given the R type.
  if (grepl('^character|^factor', data.type, ignore.case = TRUE)) {
    'text'
  } else if (grepl('^integer', data.type, ignore.case = TRUE)) {
    'integer'
  } else if (grepl('^numeric', data.type, ignore.case = TRUE)) {
    'float'
  } else if (grepl('^logical', data.type, ignore.case = TRUE)) {
    'boolean'
  } else {
    warning("Unknown data type '",data.type,"'")
    'text'
  }
}

#' write a delimited file with metadata to disk
#' 
#' This function writes a data.frame to a tab-delimited file that contains
#' special metadata in the first line. 
#' If the table includes an attribute keys', likely generated by readTbl, then it is written as additional metadata. 
#' @param df a data.frame or class that inherits from data.frame 
#' @param filename the name of a file to write or an open connection. If the file ends in .gz then it is compressed.
#' @param tablename the name for the SQL table. Default is the name of the data.frame.
#' @export
#' @examples 
#' writeTbl(my.tbl,"file.txt")
writeTbl <- function(df, filename, tablename=deparse(substitute(df)), append=FALSE) {
  
  if (inherits(filename,"connection")) {
    file.conn <- filename
  } else {
    if (append) { file.mode <- 'w+' } else { file.mode <- 'w' }
    if (grepl('.gz$', filename)) {
      file.conn <- gzfile(filename, file.mode)
    } else {
      file.conn <- file(filename, file.mode)
    }
  }

  colNames <- colnames(df)

  colTypes <- sapply(colNames, function(n) R2sql(class(df[[n]])))  

  cols <- paste(sprintf("%s{%s}", colNames, colTypes), collapse=",")
  
  keys <- attr(df, 'keys')
  if (!is.null(keys)) {
    keys <- paste0(";",keys)
  } else {
    keys <- ''
  }
  
  if (!append) {
    writeLines(sprintf("# %s: %s%s", tablename, cols, keys), file.conn)
  }

  write.table(df, file=file.conn, sep="\t", na="", row.names=FALSE, col.names=FALSE, quote=FALSE)
  
  close(file.conn)
}  
